<?php
/**
 * crud_config.php
 * Declares which database tables are exposed through the generic
 * admin CRUD screens, and any special handling per column:
 *   - encrypted: value is stored via encrypt_value()/decrypt_value()
 *                (auto-detected for VARBINARY columns, can be overridden)
 *   - type: text | textarea | email | select | color | date | datetime
 *           | readonly | password | secret | hidden
 *   - options: choices for a 'select' column
 *
 * Column metadata not explicitly listed here is inferred automatically
 * from information_schema (see crud_engine.php: get_table_meta()).
 */

declare(strict_types=1);

/** Tables editable from the admin dashboard. Acts as a hard allowlist. */
const CRUD_TABLES = [
    'user'           => 'Users',
    'user_types'     => 'User Types',
    'setup'          => 'Site Setup',
    'rsetup'         => 'Results/View Cart Display Settings',
<<<<<<< HEAD
    'uploadref'      => 'Upload Field Mapping',
=======
>>>>>>> 6c80fa6d4f8fbd6bed0b28df715056898608f570
    'path'           => 'File Paths',
    'timings'        => 'Business Hours',
    'font_and_color' => 'Fonts & Colors',
    'upload'         => 'API / Upload Config',
    'maindata'       => 'Main Data',
    'diamond_search' => 'Diamond Search Fields',
    'results'        => 'Results',
    'diamond_details' => 'Diamond Details',
    'adv_filter'      => 'Advanced Filter',
    'customer'        => 'Customers',
    'memo'            => 'Memo Details(Antwerp)',
    'dmemo'           => 'Memo Details(Dubai)',
    'cut'            => 'Cut',
    'fluorescence'   => 'Fluorescence',
    'polish'         => 'Polish',
    'symmetry'       => 'Symmetry',
    'shape'          => 'Shape',
    'location'       => 'Location',
    'size'           => 'Size',
    'lab'            => 'Lab',
    'clarity'        => 'Clarity',
    'color'          => 'Color',
    'availability'   => 'Availability',
];

/**
 * For these tables, importing from Excel first blanks out the listed
 * columns across EVERY existing row, before applying the uploaded
 * values. This means a row the uploaded file doesn't mention ends up
 * with these columns genuinely empty — a full replace rather than a
 * partial merge. Only applies to the columns listed, and only when
 * importing into that specific table.
 */
const CRUD_IMPORT_CLEAR_COLUMNS = [
    'diamond_search' => ['active', 'orderid'],
];

/**
 * All font choices offered in the searchable font-type dropdown:
 * the standard system/web-safe fonts plus the complete Google Fonts
 * catalog (1620 families total). Browsers fall back gracefully
 * to a default font for any name not actually installed/loaded.
 */
const FONT_CHOICES = [
    'ABeeZee', 'Abel', 'Abhaya Libre', 'Aboreto', 'Abril Fatface', 'Abyssinica SIL', 'Aclonica', 'Acme', 'Actor',
    'Adamina', 'ADLaM Display', 'Advent Pro', 'Agdasima', 'Aguafina Script', 'Akatab', 'Akaya Kanadaka',
    'Akaya Telivigala', 'Akronim', 'Akshar', 'Aladin', 'Alata', 'Alatsi', 'Albert Sans', 'Aldrich', 'Alef',
    'Alegreya', 'Alegreya Sans', 'Alegreya Sans SC', 'Alegreya SC', 'Aleo', 'Alex Brush', 'Alexandria',
    'Alfa Slab One', 'Alice', 'Alike', 'Alike Angular', 'Alkalami', 'Alkatra', 'Allan', 'Allerta',
    'Allerta Stencil', 'Allison', 'Allura', 'Almarai', 'Almendra', 'Almendra Display', 'Almendra SC',
    'Alumni Sans', 'Alumni Sans Collegiate One', 'Alumni Sans Inline One', 'Alumni Sans Pinstripe', 'Amarante',
    'Amaranth', 'Amatic SC', 'American Typewriter', 'Amethysta', 'Amiko', 'Amiri', 'Amiri Quran', 'Amita',
    'Anaheim', 'Andada Pro', 'Andale Mono', 'Andika', 'Anek Bangla', 'Anek Devanagari', 'Anek Gujarati',
    'Anek Gurmukhi', 'Anek Kannada', 'Anek Latin', 'Anek Malayalam', 'Anek Odia', 'Anek Tamil', 'Anek Telugu',
    'Angkor', 'Annie Use Your Telescope', 'Anonymous Pro', 'Antic', 'Antic Didone', 'Antic Slab', 'Anton',
    'Antonio', 'Anuphan', 'Anybody', 'Aoboshi One', 'AR One Sans', 'Arapey', 'Arbutus', 'Arbutus Slab',
    'Architects Daughter', 'Archivo', 'Archivo Black', 'Archivo Narrow', 'Are You Serious', 'Aref Ruqaa',
    'Aref Ruqaa Ink', 'Arial', 'Arial Black', 'Arima', 'Arima Madurai', 'Arimo', 'Arizonia', 'Armata', 'Arsenal',
    'Artifika', 'Arvo', 'Arya', 'Asap', 'Asap Condensed', 'Asar', 'Asset', 'Assistant', 'Astloch', 'Asul',
    'Athiti', 'Atkinson Hyperlegible', 'Atma', 'Atomic Age', 'Aubrey', 'Audiowide', 'Autour One', 'Average',
    'Average Sans', 'Averia Gruesa Libre', 'Averia Libre', 'Averia Sans Libre', 'Averia Serif Libre',
    'Azeret Mono', 'B612', 'B612 Mono', 'Babylonica', 'Bacasime Antique', 'Bad Script', 'Bagel Fat One', 'Bahiana',
    'Bahianita', 'Bai Jamjuree', 'Bakbak One', 'Ballet', 'Baloo 2', 'Baloo Bhai 2', 'Baloo Bhaijaan 2',
    'Baloo Bhaina 2', 'Baloo Chettan 2', 'Baloo Da 2', 'Baloo Paaji 2', 'Baloo Tamma 2', 'Baloo Tammudu 2',
    'Baloo Thambi 2', 'Balsamiq Sans', 'Balthazar', 'Bangers', 'Barlow', 'Barlow Condensed',
    'Barlow Semi Condensed', 'Barriecito', 'Barrio', 'Basic', 'Baskerville', 'Baskervville', 'Battambang',
    'Baumans', 'Bayon', 'Be Vietnam Pro', 'Beau Rivage', 'Bebas Neue', 'Belanosima', 'Belgrano', 'Bellefair',
    'Belleza', 'Bellota', 'Bellota Text', 'BenchNine', 'Benne', 'Bentham', 'Berkshire Swash', 'Besley',
    'Beth Ellen', 'Bevan', 'BhuTuka Expanded One', 'Big Shoulders Display', 'Big Shoulders Inline Display',
    'Big Shoulders Inline Text', 'Big Shoulders Stencil Display', 'Big Shoulders Stencil Text',
    'Big Shoulders Text', 'Bigelow Rules', 'Bigshot One', 'Bilbo', 'Bilbo Swash Caps', 'BioRhyme',
    'BioRhyme Expanded', 'Birthstone', 'Birthstone Bounce', 'Biryani', 'Bitter', 'BIZ UDGothic', 'BIZ UDMincho',
    'BIZ UDPGothic', 'BIZ UDPMincho', 'Black And White Picture', 'Black Han Sans', 'Black Ops One', 'Blaka',
    'Blaka Hollow', 'Blaka Ink', 'Blinker', 'Bodoni Moda', 'Bokor', 'Bona Nova', 'Bonbon', 'Bonheur Royale',
    'Boogaloo', 'Bookman', 'Borel', 'Bowlby One', 'Bowlby One SC', 'Braah One', 'Brawler', 'Bree Serif',
    'Bricolage Grotesque', 'Bruno Ace', 'Bruno Ace SC', 'Brush Script MT', 'Brygada 1918', 'Bubblegum Sans',
    'Bubbler One', 'Buda', 'Buenard', 'Bungee', 'Bungee Hairline', 'Bungee Inline', 'Bungee Outline',
    'Bungee Shade', 'Bungee Spice', 'Butcherman', 'Butterfly Kids', 'Cabin', 'Cabin Condensed', 'Cabin Sketch',
    'Caesar Dressing', 'Cagliostro', 'Cairo', 'Cairo Play', 'Caladea', 'Calibri', 'Calistoga', 'Calligraffitti',
    'Cambay', 'Cambo', 'Cambria', 'Candal', 'Candara', 'Cantarell', 'Cantata One', 'Cantora One', 'Caprasimo',
    'Capriola', 'Caramel', 'Carattere', 'Cardo', 'Carlito', 'Carme', 'Carrois Gothic', 'Carrois Gothic SC',
    'Carter One', 'Castoro', 'Castoro Titling', 'Catamaran', 'Caudex', 'Caveat', 'Caveat Brush',
    'Cedarville Cursive', 'Century Gothic', 'Ceviche One', 'Chakra Petch', 'Changa', 'Changa One', 'Chango',
    'Charis SIL', 'Charm', 'Charmonman', 'Chathura', 'Chau Philomene One', 'Chela One', 'Chelsea Market', 'Chenla',
    'Cherish', 'Cherry Bomb One', 'Cherry Cream Soda', 'Cherry Swash', 'Chewy', 'Chicle', 'Chilanka', 'Chivo',
    'Chivo Mono', 'Chokokutai', 'Chonburi', 'Cinzel', 'Cinzel Decorative', 'Clicker Script', 'Climate Crisis',
    'Coda', 'Coda Caption', 'Codystar', 'Coiny', 'Combo', 'Comfortaa', 'Comforter', 'Comforter Brush',
    'Comic Neue', 'Comic Sans MS', 'Coming Soon', 'Comme', 'Commissioner', 'Concert One', 'Condiment', 'Consolas',
    'Constantia', 'Content', 'Contrail One', 'Convergence', 'Cookie', 'Copperplate', 'Copse', 'Corbel', 'Corben',
    'Corinthia', 'Cormorant', 'Cormorant Garamond', 'Cormorant Infant', 'Cormorant SC', 'Cormorant Unicase',
    'Cormorant Upright', 'Courgette', 'Courier New', 'Courier Prime', 'Cousine', 'Coustard',
    'Covered By Your Grace', 'Crafty Girls', 'Creepster', 'Crete Round', 'Crimson Pro', 'Crimson Text',
    'Croissant One', 'Crushed', 'Cuprum', 'Cute Font', 'Cutive', 'Cutive Mono', 'Dai Banna SIL', 'Damion',
    'Dancing Script', 'Dangrek', 'Darker Grotesque', 'Darumadrop One', 'David Libre', 'Dawning of a New Day',
    'Days One', 'Dekko', 'Dela Gothic One', 'Delicious Handrawn', 'Delius', 'Delius Swash Caps', 'Delius Unicase',
    'Della Respira', 'Denk One', 'Devonshire', 'Dhurjati', 'Didact Gothic', 'Didot', 'Diphylleia', 'Diplomata',
    'Diplomata SC', 'DM Mono', 'DM Sans', 'DM Serif Display', 'DM Serif Text', 'Do Hyeon', 'Dokdo', 'Domine',
    'Donegal One', 'Dongle', 'Doppio One', 'Dorsa', 'Dosis', 'DotGothic16', 'Dr Sugiyama', 'Duru Sans',
    'Dynalight', 'DynaPuff', 'Eagle Lake', 'East Sea Dokdo', 'Eater', 'EB Garamond', 'Economica', 'Eczar',
    'Edu NSW ACT Foundation', 'Edu QLD Beginner', 'Edu SA Beginner', 'Edu TAS Beginner', 'Edu VIC WA NT Beginner',
    'El Messiri', 'Electrolize', 'Elsie', 'Elsie Swash Caps', 'Emblema One', 'Emilys Candy', 'Encode Sans',
    'Encode Sans Condensed', 'Encode Sans Expanded', 'Encode Sans SC', 'Encode Sans Semi Condensed',
    'Encode Sans Semi Expanded', 'Engagement', 'Englebert', 'Enriqueta', 'Ephesis', 'Epilogue', 'Erica One',
    'Esteban', 'Estonia', 'Euphoria Script', 'Ewert', 'Exo', 'Exo 2', 'Expletus Sans', 'Explora', 'Fahkwang',
    'Familjen Grotesk', 'Fanwood Text', 'Farro', 'Farsan', 'Fascinate', 'Fascinate Inline', 'Faster One',
    'Fasthand', 'Fauna One', 'Faustina', 'Federant', 'Federo', 'Felipa', 'Fenix', 'Festive', 'Figtree',
    'Finger Paint', 'Finlandica', 'Fira Code', 'Fira Mono', 'Fira Sans', 'Fira Sans Condensed',
    'Fira Sans Extra Condensed', 'Fjalla One', 'Fjord One', 'Flamenco', 'Flavors', 'Fleur De Leah', 'Flow Block',
    'Flow Circular', 'Flow Rounded', 'Foldit', 'Fondamento', 'Fontdiner Swanky', 'Forum', 'Fragment Mono',
    'Francois One', 'Frank Ruhl Libre', 'Franklin Gothic Medium', 'Fraunces', 'Freckle Face',
    'Fredericka the Great', 'Fredoka', 'Freehand', 'Fresca', 'Frijole', 'Fruktur', 'Fugaz One', 'Fuggles',
    'Futura', 'Fuzzy Bubbles', 'Gabarito', 'Gabriela', 'Gaegu', 'Gafata', 'Gajraj One', 'Galada', 'Galdeano',
    'Galindo', 'Gamja Flower', 'Gantari', 'Garamond', 'Gasoek One', 'Gayathri', 'Gelasio', 'Gemunu Libre', 'Genos',
    'Gentium Book Plus', 'Gentium Plus', 'Geo', 'Geologica', 'Georama', 'Georgia', 'Geostar', 'Geostar Fill',
    'Germania One', 'GFS Didot', 'GFS Neohellenic', 'Gideon Roman', 'Gidugu', 'Gilda Display', 'Gill Sans',
    'Girassol', 'Give You Glory', 'Glass Antiqua', 'Glegoo', 'Gloock', 'Gloria Hallelujah', 'Glory', 'Gluten',
    'Goblin One', 'Gochi Hand', 'Goldman', 'Golos Text', 'Gorditas', 'Gothic A1', 'Gotu', 'Goudy Bookletter 1911',
    'Gowun Batang', 'Gowun Dodum', 'Graduate', 'Grand Hotel', 'Grandiflora One', 'Grandstander', 'Grape Nuts',
    'Gravitas One', 'Great Vibes', 'Grechen Fuemen', 'Grenze', 'Grenze Gotisch', 'Grey Qo', 'Griffy', 'Gruppo',
    'Gudea', 'Gugi', 'Gulzar', 'Gupter', 'Gurajada', 'Gwendolyn', 'Habibi', 'Hachi Maru Pop', 'Hahmlet', 'Halant',
    'Hammersmith One', 'Hanalei', 'Hanalei Fill', 'Handjet', 'Handlee', 'Hanken Grotesk', 'Hanuman',
    'Happy Monkey', 'Harmattan', 'Headland One', 'Heebo', 'Helvetica', 'Henny Penny', 'Hepta Slab',
    'Herr Von Muellerhoff', 'Hi Melody', 'Hina Mincho', 'Hind', 'Hind Guntur', 'Hind Madurai', 'Hind Siliguri',
    'Hind Vadodara', 'Holtwood One SC', 'Homemade Apple', 'Homenaje', 'Hubballi', 'Hurricane', 'Ibarra Real Nova',
    'IBM Plex Mono', 'IBM Plex Sans', 'IBM Plex Sans Arabic', 'IBM Plex Sans Condensed',
    'IBM Plex Sans Devanagari', 'IBM Plex Sans Hebrew', 'IBM Plex Sans JP', 'IBM Plex Sans KR',
    'IBM Plex Sans Thai', 'IBM Plex Sans Thai Looped', 'IBM Plex Serif', 'Iceberg', 'Iceland',
    'IM Fell Double Pica', 'IM Fell Double Pica SC', 'IM Fell DW Pica', 'IM Fell DW Pica SC', 'IM Fell English',
    'IM Fell English SC', 'IM Fell French Canon', 'IM Fell French Canon SC', 'IM Fell Great Primer',
    'IM Fell Great Primer SC', 'Imbue', 'Impact', 'Imperial Script', 'Imprima', 'Inclusive Sans', 'Inconsolata',
    'Inder', 'Indie Flower', 'Ingrid Darling', 'Inika', 'Inknut Antiqua', 'Inria Sans', 'Inria Serif',
    'Inspiration', 'Instrument Sans', 'Instrument Serif', 'Inter', 'Inter Tight', 'Irish Grover', 'Island Moments',
    'Istok Web', 'Italiana', 'Italianno', 'Itim', 'Jacques Francois', 'Jacques Francois Shadow', 'Jaldi',
    'JetBrains Mono', 'Jim Nightshade', 'Joan', 'Jockey One', 'Jolly Lodger', 'Jomhuria', 'Jomolhari',
    'Josefin Sans', 'Josefin Slab', 'Jost', 'Joti One', 'Jua', 'Judson', 'Julee', 'Julius Sans One', 'Junge',
    'Jura', 'Just Another Hand', 'Just Me Again Down Here', 'K2D', 'Kablammo', 'Kadwa', 'Kaisei Decol',
    'Kaisei HarunoUmi', 'Kaisei Opti', 'Kaisei Tokumin', 'Kalam', 'Kameron', 'Kanit', 'Kantumruy Pro', 'Karantina',
    'Karla', 'Karma', 'Katibeh', 'Kaushan Script', 'Kavivanar', 'Kavoon', 'Kdam Thmor Pro', 'Keania One',
    'Kelly Slab', 'Kenia', 'Khand', 'Khmer', 'Khula', 'Kings', 'Kirang Haerang', 'Kite One', 'Kiwi Maru',
    'Klee One', 'Knewave', 'Kodchasan', 'Koh Santepheap', 'KoHo', 'Kolker Brush', 'Konkhmer Sleokchher', 'Kosugi',
    'Kosugi Maru', 'Kotta One', 'Koulen', 'Kranky', 'Kreon', 'Kristi', 'Krona One', 'Krub', 'Kufam', 'Kulim Park',
    'Kumar One', 'Kumar One Outline', 'Kumbh Sans', 'Kurale', 'La Belle Aurore', 'Labrada', 'Lacquer', 'Laila',
    'Lakki Reddy', 'Lalezar', 'Lancelot', 'Langar', 'Lateef', 'Lato', 'Lavishly Yours', 'League Gothic',
    'League Script', 'League Spartan', 'Leckerli One', 'Ledger', 'Lekton', 'Lemon', 'Lemonada', 'Lexend',
    'Lexend Deca', 'Lexend Exa', 'Lexend Giga', 'Lexend Mega', 'Lexend Peta', 'Lexend Tera', 'Lexend Zetta',
    'Libre Barcode 128', 'Libre Barcode 128 Text', 'Libre Barcode 39', 'Libre Barcode 39 Extended',
    'Libre Barcode 39 Extended Text', 'Libre Barcode 39 Text', 'Libre Barcode EAN13 Text', 'Libre Baskerville',
    'Libre Bodoni', 'Libre Caslon Display', 'Libre Caslon Text', 'Libre Franklin', 'Licorice', 'Life Savers',
    'Lilita One', 'Lily Script One', 'Limelight', 'Linden Hill', 'Lisu Bosa', 'Literata', 'Liu Jian Mao Cao',
    'Livvic', 'Lobster', 'Lobster Two', 'Londrina Outline', 'Londrina Shadow', 'Londrina Sketch', 'Londrina Solid',
    'Long Cang', 'Lora', 'Love Light', 'Love Ya Like A Sister', 'Loved by the King', 'Lovers Quarrel',
    'Lucida Console', 'Lucida Sans Unicode', 'Luckiest Guy', 'Lugrasimo', 'Lumanosimo', 'Lunasima', 'Lusitana',
    'Lustria', 'Luxurious Roman', 'Luxurious Script', 'M PLUS 1', 'M PLUS 1 Code', 'M PLUS 1p', 'M PLUS 2',
    'M PLUS Code Latin', 'M PLUS Rounded 1c', 'Ma Shan Zheng', 'Macondo', 'Macondo Swash Caps', 'Mada', 'Magra',
    'Maiden Orange', 'Maitree', 'Major Mono Display', 'Mako', 'Mali', 'Mallanna', 'Mandali', 'Manjari', 'Manrope',
    'Mansalva', 'Manuale', 'Marcellus', 'Marcellus SC', 'Marck Script', 'Margarine', 'Marhey', 'Markazi Text',
    'Marko One', 'Marmelad', 'Martel', 'Martel Sans', 'Martian Mono', 'Marvel', 'Mate', 'Mate SC',
    'Material Icons', 'Material Icons Outlined', 'Material Icons Round', 'Material Icons Sharp',
    'Material Icons Two Tone', 'Material Symbols Outlined', 'Material Symbols Rounded', 'Material Symbols Sharp',
    'Maven Pro', 'McLaren', 'Mea Culpa', 'Meddon', 'MedievalSharp', 'Medula One', 'Meera Inimai', 'Megrim',
    'Meie Script', 'Menlo', 'Meow Script', 'Merienda', 'Merriweather', 'Merriweather Sans', 'Metal', 'Metal Mania',
    'Metamorphous', 'Metrophobic', 'Michroma', 'Milonga', 'Miltonian', 'Miltonian Tattoo', 'Mina', 'Mingzat',
    'Miniver', 'Miriam Libre', 'Mirza', 'Miss Fajardose', 'Mitr', 'Mochiy Pop One', 'Mochiy Pop P One', 'Modak',
    'Modern Antiqua', 'Mogra', 'Mohave', 'Moirai One', 'Molengo', 'Molle', 'Monaco', 'Monda', 'Monofett',
    'Monomaniac One', 'Monoton', 'Monsieur La Doulaise', 'Montaga', 'Montagu Slab', 'MonteCarlo', 'Montez',
    'Montserrat', 'Montserrat Alternates', 'Montserrat Subrayada', 'Moo Lah Lah', 'Mooli', 'Moon Dance', 'Moul',
    'Moulpali', 'Mountains of Christmas', 'Mouse Memoirs', 'Mr Bedfort', 'Mr Dafoe', 'Mr De Haviland',
    'Mrs Saint Delafield', 'Mrs Sheppards', 'Ms Madi', 'Mukta', 'Mukta Mahee', 'Mukta Malar', 'Mukta Vaani',
    'Mulish', 'Murecho', 'MuseoModerno', 'My Soul', 'Mynerve', 'Mystery Quest', 'Nabla', 'Nanum Brush Script',
    'Nanum Gothic', 'Nanum Gothic Coding', 'Nanum Myeongjo', 'Nanum Pen Script', 'Narnoor', 'Neonderthaw',
    'Nerko One', 'Neucha', 'Neuton', 'New Rocker', 'New Tegomin', 'News Cycle', 'Newsreader', 'Niconne', 'Niramit',
    'Nixie One', 'Nobile', 'Nokora', 'Norican', 'Nosifer', 'Notable', 'Nothing You Could Do', 'Noticia Text',
    'Noto Color Emoji', 'Noto Emoji', 'Noto Kufi Arabic', 'Noto Music', 'Noto Naskh Arabic', 'Noto Nastaliq Urdu',
    'Noto Rashi Hebrew', 'Noto Sans', 'Noto Sans Adlam', 'Noto Sans Adlam Unjoined',
    'Noto Sans Anatolian Hieroglyphs', 'Noto Sans Arabic', 'Noto Sans Armenian', 'Noto Sans Avestan',
    'Noto Sans Balinese', 'Noto Sans Bamum', 'Noto Sans Bassa Vah', 'Noto Sans Batak', 'Noto Sans Bengali',
    'Noto Sans Bhaiksuki', 'Noto Sans Brahmi', 'Noto Sans Buginese', 'Noto Sans Buhid',
    'Noto Sans Canadian Aboriginal', 'Noto Sans Carian', 'Noto Sans Caucasian Albanian', 'Noto Sans Chakma',
    'Noto Sans Cham', 'Noto Sans Cherokee', 'Noto Sans Chorasmian', 'Noto Sans Coptic', 'Noto Sans Cuneiform',
    'Noto Sans Cypriot', 'Noto Sans Cypro Minoan', 'Noto Sans Deseret', 'Noto Sans Devanagari',
    'Noto Sans Display', 'Noto Sans Duployan', 'Noto Sans Egyptian Hieroglyphs', 'Noto Sans Elbasan',
    'Noto Sans Elymaic', 'Noto Sans Ethiopic', 'Noto Sans Georgian', 'Noto Sans Glagolitic', 'Noto Sans Gothic',
    'Noto Sans Grantha', 'Noto Sans Gujarati', 'Noto Sans Gunjala Gondi', 'Noto Sans Gurmukhi',
    'Noto Sans Hanifi Rohingya', 'Noto Sans Hanunoo', 'Noto Sans Hatran', 'Noto Sans Hebrew', 'Noto Sans HK',
    'Noto Sans Imperial Aramaic', 'Noto Sans Indic Siyaq Numbers', 'Noto Sans Inscriptional Pahlavi',
    'Noto Sans Inscriptional Parthian', 'Noto Sans Javanese', 'Noto Sans JP', 'Noto Sans Kaithi',
    'Noto Sans Kannada', 'Noto Sans Kayah Li', 'Noto Sans Kharoshthi', 'Noto Sans Khmer', 'Noto Sans Khojki',
    'Noto Sans Khudawadi', 'Noto Sans KR', 'Noto Sans Lao', 'Noto Sans Lao Looped', 'Noto Sans Lepcha',
    'Noto Sans Limbu', 'Noto Sans Linear A', 'Noto Sans Linear B', 'Noto Sans Lisu', 'Noto Sans Lycian',
    'Noto Sans Lydian', 'Noto Sans Mahajani', 'Noto Sans Malayalam', 'Noto Sans Mandaic', 'Noto Sans Manichaean',
    'Noto Sans Marchen', 'Noto Sans Masaram Gondi', 'Noto Sans Math', 'Noto Sans Mayan Numerals',
    'Noto Sans Medefaidrin', 'Noto Sans Meetei Mayek', 'Noto Sans Mende Kikakui', 'Noto Sans Meroitic',
    'Noto Sans Miao', 'Noto Sans Modi', 'Noto Sans Mongolian', 'Noto Sans Mono', 'Noto Sans Mro',
    'Noto Sans Multani', 'Noto Sans Myanmar', 'Noto Sans Nabataean', 'Noto Sans Nag Mundari',
    'Noto Sans Nandinagari', 'Noto Sans New Tai Lue', 'Noto Sans Newa', 'Noto Sans NKo', 'Noto Sans NKo Unjoined',
    'Noto Sans Nushu', 'Noto Sans Ogham', 'Noto Sans Ol Chiki', 'Noto Sans Old Hungarian', 'Noto Sans Old Italic',
    'Noto Sans Old North Arabian', 'Noto Sans Old Permic', 'Noto Sans Old Persian', 'Noto Sans Old Sogdian',
    'Noto Sans Old South Arabian', 'Noto Sans Old Turkic', 'Noto Sans Oriya', 'Noto Sans Osage',
    'Noto Sans Osmanya', 'Noto Sans Pahawh Hmong', 'Noto Sans Palmyrene', 'Noto Sans Pau Cin Hau',
    'Noto Sans Phags Pa', 'Noto Sans Phoenician', 'Noto Sans Psalter Pahlavi', 'Noto Sans Rejang',
    'Noto Sans Runic', 'Noto Sans Samaritan', 'Noto Sans Saurashtra', 'Noto Sans SC', 'Noto Sans Sharada',
    'Noto Sans Shavian', 'Noto Sans Siddham', 'Noto Sans SignWriting', 'Noto Sans Sinhala', 'Noto Sans Sogdian',
    'Noto Sans Sora Sompeng', 'Noto Sans Soyombo', 'Noto Sans Sundanese', 'Noto Sans Syloti Nagri',
    'Noto Sans Symbols', 'Noto Sans Symbols 2', 'Noto Sans Syriac', 'Noto Sans Syriac Eastern',
    'Noto Sans Tagalog', 'Noto Sans Tagbanwa', 'Noto Sans Tai Le', 'Noto Sans Tai Tham', 'Noto Sans Tai Viet',
    'Noto Sans Takri', 'Noto Sans Tamil', 'Noto Sans Tamil Supplement', 'Noto Sans Tangsa', 'Noto Sans TC',
    'Noto Sans Telugu', 'Noto Sans Thaana', 'Noto Sans Thai', 'Noto Sans Thai Looped', 'Noto Sans Tifinagh',
    'Noto Sans Tirhuta', 'Noto Sans Ugaritic', 'Noto Sans Vai', 'Noto Sans Vithkuqi', 'Noto Sans Wancho',
    'Noto Sans Warang Citi', 'Noto Sans Yi', 'Noto Sans Zanabazar Square', 'Noto Serif', 'Noto Serif Ahom',
    'Noto Serif Armenian', 'Noto Serif Balinese', 'Noto Serif Bengali', 'Noto Serif Devanagari',
    'Noto Serif Display', 'Noto Serif Dogra', 'Noto Serif Ethiopic', 'Noto Serif Georgian', 'Noto Serif Grantha',
    'Noto Serif Gujarati', 'Noto Serif Gurmukhi', 'Noto Serif Hebrew', 'Noto Serif HK', 'Noto Serif JP',
    'Noto Serif Kannada', 'Noto Serif Khitan Small Script', 'Noto Serif Khmer', 'Noto Serif Khojki',
    'Noto Serif KR', 'Noto Serif Lao', 'Noto Serif Makasar', 'Noto Serif Malayalam', 'Noto Serif Myanmar',
    'Noto Serif NP Hmong', 'Noto Serif Oriya', 'Noto Serif Ottoman Siyaq', 'Noto Serif SC', 'Noto Serif Sinhala',
    'Noto Serif Tamil', 'Noto Serif Tangut', 'Noto Serif TC', 'Noto Serif Telugu', 'Noto Serif Thai',
    'Noto Serif Tibetan', 'Noto Serif Toto', 'Noto Serif Vithkuqi', 'Noto Serif Yezidi', 'Noto Traditional Nushu',
    'Nova Cut', 'Nova Flat', 'Nova Mono', 'Nova Oval', 'Nova Round', 'Nova Script', 'Nova Slim', 'Nova Square',
    'NTR', 'Numans', 'Nunito', 'Nunito Sans', 'Nuosu SIL', 'Odibee Sans', 'Odor Mean Chey', 'Offside', 'Oi',
    'Old Standard TT', 'Oldenburg', 'Ole', 'Oleo Script', 'Oleo Script Swash Caps', 'Onest', 'Oooh Baby',
    'Open Sans', 'Optima', 'Oranienbaum', 'Orbit', 'Orbitron', 'Oregano', 'Orelega One', 'Orienta',
    'Original Surfer', 'Oswald', 'Outfit', 'Over the Rainbow', 'Overlock', 'Overlock SC', 'Overpass',
    'Overpass Mono', 'Ovo', 'Oxanium', 'Oxygen', 'Oxygen Mono', 'Pacifico', 'Padauk', 'Padyakke Expanded One',
    'Palanquin', 'Palanquin Dark', 'Palatino Linotype', 'Palette Mosaic', 'Pangolin', 'Paprika', 'Papyrus',
    'Parisienne', 'Passero One', 'Passion One', 'Passions Conflict', 'Pathway Extreme', 'Pathway Gothic One',
    'Patrick Hand', 'Patrick Hand SC', 'Pattaya', 'Patua One', 'Pavanam', 'Paytone One', 'Peddana', 'Peralta',
    'Permanent Marker', 'Perpetua', 'Petemoss', 'Petit Formal Script', 'Petrona', 'Philosopher', 'Phudu',
    'Piazzolla', 'Piedra', 'Pinyon Script', 'Pirata One', 'Pixelify Sans', 'Plaster', 'Play', 'Playball',
    'Playfair', 'Playfair Display', 'Playfair Display SC', 'Playpen Sans', 'Plus Jakarta Sans', 'Podkova',
    'Poiret One', 'Poller One', 'Poltawski Nowy', 'Poly', 'Pompiere', 'Pontano Sans', 'Poor Story', 'Poppins',
    'Port Lligat Sans', 'Port Lligat Slab', 'Potta One', 'Pragati Narrow', 'Praise', 'Prata', 'Preahvihear',
    'Press Start 2P', 'Pridi', 'Princess Sofia', 'Prociono', 'Prompt', 'Prosto One', 'Proza Libre', 'PT Mono',
    'PT Sans', 'PT Sans Caption', 'PT Sans Narrow', 'PT Serif', 'PT Serif Caption', 'Public Sans', 'Puppies Play',
    'Puritan', 'Purple Purse', 'Qahiri', 'Quando', 'Quantico', 'Quattrocento', 'Quattrocento Sans', 'Questrial',
    'Quicksand', 'Quintessential', 'Qwigley', 'Qwitcher Grypen', 'Racing Sans One', 'Radio Canada', 'Radley',
    'Rajdhani', 'Rakkas', 'Raleway', 'Raleway Dots', 'Ramabhadra', 'Ramaraja', 'Rambla', 'Rammetto One',
    'Rampart One', 'Ranchers', 'Rancho', 'Ranga', 'Rasa', 'Rationale', 'Ravi Prakash', 'Readex Pro', 'Recursive',
    'Red Hat Display', 'Red Hat Mono', 'Red Hat Text', 'Red Rose', 'Redacted', 'Redacted Script', 'Redressed',
    'Reem Kufi', 'Reem Kufi Fun', 'Reem Kufi Ink', 'Reenie Beanie', 'Reggae One', 'REM', 'Revalia',
    'Rhodium Libre', 'Ribeye', 'Ribeye Marrow', 'Righteous', 'Risque', 'Road Rage', 'Roboto', 'Roboto Condensed',
    'Roboto Flex', 'Roboto Mono', 'Roboto Serif', 'Roboto Slab', 'Rochester', 'Rock 3D', 'Rock Salt',
    'RocknRoll One', 'Rockwell', 'Rokkitt', 'Romanesco', 'Ropa Sans', 'Rosario', 'Rosarivo', 'Rouge Script',
    'Rowdies', 'Rozha One', 'Rubik', 'Rubik 80s Fade', 'Rubik Beastly', 'Rubik Bubbles', 'Rubik Burned',
    'Rubik Dirt', 'Rubik Distressed', 'Rubik Gemstones', 'Rubik Glitch', 'Rubik Iso', 'Rubik Marker Hatch',
    'Rubik Maze', 'Rubik Microbe', 'Rubik Mono One', 'Rubik Moonrocks', 'Rubik Pixels', 'Rubik Puddles',
    'Rubik Spray Paint', 'Rubik Storm', 'Rubik Vinyl', 'Rubik Wet Paint', 'Ruda', 'Rufina', 'Ruge Boogie',
    'Ruluko', 'Rum Raisin', 'Ruslan Display', 'Russo One', 'Ruthie', 'Ruwudu', 'Rye', 'Sacramento', 'Sahitya',
    'Sail', 'Saira', 'Saira Condensed', 'Saira Extra Condensed', 'Saira Semi Condensed', 'Saira Stencil One',
    'Salsa', 'Sanchez', 'Sancreek', 'Sansita', 'Sansita Swashed', 'Sarabun', 'Sarala', 'Sarina', 'Sarpanch',
    'Sassy Frass', 'Satisfy', 'Sawarabi Gothic', 'Sawarabi Mincho', 'Scada', 'Scheherazade New',
    'Schibsted Grotesk', 'Schoolbell', 'Scope One', 'Seaweed Script', 'Secular One', 'Sedgwick Ave',
    'Sedgwick Ave Display', 'Segoe UI', 'Sen', 'Send Flowers', 'Sevillana', 'Seymour One', 'Shadows Into Light',
    'Shadows Into Light Two', 'Shalimar', 'Shantell Sans', 'Shanti', 'Share', 'Share Tech', 'Share Tech Mono',
    'Shippori Antique', 'Shippori Antique B1', 'Shippori Mincho', 'Shippori Mincho B1', 'Shizuru', 'Shojumaru',
    'Short Stack', 'Shrikhand', 'Siemreap', 'Sigmar', 'Sigmar One', 'Signika', 'Signika Negative', 'Silkscreen',
    'Simonetta', 'Single Day', 'Sintony', 'Sirin Stencil', 'Six Caps', 'Skranji', 'Slabo 13px', 'Slabo 27px',
    'Slackey', 'Slackside One', 'Smokum', 'Smooch', 'Smooch Sans', 'Smythe', 'Sniglet', 'Snippet', 'Snowburst One',
    'Sofadi One', 'Sofia', 'Sofia Sans', 'Sofia Sans Condensed', 'Sofia Sans Extra Condensed',
    'Sofia Sans Semi Condensed', 'Solitreo', 'Solway', 'Sometype Mono', 'Song Myung', 'Sono', 'Sonsie One', 'Sora',
    'Sorts Mill Goudy', 'Source Code Pro', 'Source Sans 3', 'Source Serif 4', 'Space Grotesk', 'Space Mono',
    'Special Elite', 'Spectral', 'Spectral SC', 'Spicy Rice', 'Spinnaker', 'Spirax', 'Splash', 'Spline Sans',
    'Spline Sans Mono', 'Squada One', 'Square Peg', 'Sree Krushnadevaraya', 'Sriracha', 'Srisakdi', 'Staatliches',
    'Stalemate', 'Stalinist One', 'Stardos Stencil', 'Stick', 'Stick No Bills', 'Stint Ultra Condensed',
    'Stint Ultra Expanded', 'STIX Two Text', 'Stoke', 'Strait', 'Style Script', 'Stylish', 'Sue Ellen Francisco',
    'Suez One', 'Sulphur Point', 'Sumana', 'Sunflower', 'Sunshiney', 'Supermercado One', 'Sura', 'Suranna',
    'Suravaram', 'Suwannaphum', 'Swanky and Moo Moo', 'Syncopate', 'Syne', 'Syne Mono', 'Syne Tactile', 'Tahoma',
    'Tai Heritage Pro', 'Tajawal', 'Tangerine', 'Tapestry', 'Taprom', 'Tauri', 'Taviraj', 'Teko', 'Tektur',
    'Telex', 'Tenali Ramakrishna', 'Tenor Sans', 'Text Me One', 'Texturina', 'Thasadith', 'The Girl Next Door',
    'The Nautigal', 'Tienne', 'Tillana', 'Tilt Neon', 'Tilt Prism', 'Tilt Warp', 'Times New Roman', 'Timmana',
    'Tinos', 'Tiro Bangla', 'Tiro Devanagari Hindi', 'Tiro Devanagari Marathi', 'Tiro Devanagari Sanskrit',
    'Tiro Gurmukhi', 'Tiro Kannada', 'Tiro Tamil', 'Tiro Telugu', 'Titan One', 'Titillium Web', 'Tomorrow',
    'Tourney', 'Trade Winds', 'Train One', 'Trebuchet MS', 'Trirong', 'Trispace', 'Trocchi', 'Trochut',
    'Truculenta', 'Trykker', 'Tsukimi Rounded', 'Tulpen One', 'Turret Road', 'Twinkle Star', 'Ubuntu',
    'Ubuntu Condensed', 'Ubuntu Mono', 'Uchen', 'Ultra', 'Unbounded', 'Uncial Antiqua', 'Underdog', 'Unica One',
    'UnifrakturCook', 'UnifrakturMaguntia', 'Unkempt', 'Unlock', 'Unna', 'Updock', 'Urbanist', 'Vampiro One',
    'Varela', 'Varela Round', 'Varta', 'Vast Shadow', 'Vazirmatn', 'Verdana', 'Vesper Libre', 'Viaoda Libre',
    'Vibes', 'Vibur', 'Victor Mono', 'Vidaloka', 'Viga', 'Vina Sans', 'Voces', 'Volkhov', 'Vollkorn',
    'Vollkorn SC', 'Voltaire', 'VT323', 'Vujahday Script', 'Waiting for the Sunrise', 'Wallpoet',
    'Walter Turncoat', 'Warnes', 'Water Brush', 'Waterfall', 'Wavefont', 'Wellfleet', 'Wendy One', 'Whisper',
    'WindSong', 'Wire One', 'Wix Madefor Display', 'Wix Madefor Text', 'Work Sans', 'Xanh Mono', 'Yaldevi',
    'Yanone Kaffeesatz', 'Yantramanav', 'Yatra One', 'Yellowtail', 'Yeon Sung', 'Yeseva One', 'Yesteryear',
    'Yomogi', 'Young Serif', 'Yrsa', 'Ysabeau', 'Ysabeau Infant', 'Ysabeau Office', 'Ysabeau SC', 'Yuji Boku',
    'Yuji Hentaigana Akari', 'Yuji Hentaigana Akebono', 'Yuji Mai', 'Yuji Syuku', 'Yusei Magic', 'ZCOOL KuaiLe',
    'ZCOOL QingKe HuangYou', 'ZCOOL XiaoWei', 'Zen Antique', 'Zen Antique Soft', 'Zen Dots',
    'Zen Kaku Gothic Antique', 'Zen Kaku Gothic New', 'Zen Kurenaido', 'Zen Loop', 'Zen Maru Gothic',
    'Zen Old Mincho', 'Zen Tokyo Zoo', 'Zeyada', 'Zhi Mang Xing', 'Zilla Slab', 'Zilla Slab Highlight'
];

/** Per-column overrides, keyed by table then column name. */
const CRUD_COLUMN_OVERRIDES = [
    'user' => [
        'id'              => ['type' => 'readonly'],
        'emailid'         => ['type' => 'email', 'label' => 'Email'],
        'emailid_hash'    => ['type' => 'hidden'],
        'password'        => ['type' => 'password', 'label' => 'Password'],
        'usertype'        => ['type' => 'lookup', 'label' => 'User Type',
                               'lookup_table' => 'user_types', 'lookup_value' => 'id', 'lookup_display' => 'usertype'],
        'approval'        => ['type' => 'select', 'label' => 'Approval',
                               'options' => ['pending', 'approved', 'rejected', 'disabled']],
        'creation_date'   => ['type' => 'readonly', 'label' => 'Created'],
        'last_login'      => ['type' => 'readonly', 'label' => 'Last Login'],
        'locked_until'    => ['type' => 'readonly', 'label' => 'Locked Until'],
        'failed_attempts' => ['type' => 'readonly', 'label' => 'Failed Attempts'],
        'ipadd'           => ['type' => 'readonly', 'label' => 'Last IP'],
    ],
    'user_types' => [
        'id'       => ['type' => 'readonly'],
        'usertype' => ['label' => 'Type Name'],
        'level'    => ['type' => 'select', 'label' => 'Level',
                       'options' => ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
                       'hint' => 'Levels 0-7 are custom user roles (user module only). 8 = Admin (user + admin modules). 9 = Super Admin (all modules).'],
    ],
    'setup' => [
        'id'         => ['type' => 'readonly'],
        'Page Desc'  => ['type' => 'textarea'],
        'Meta Desc'  => ['type' => 'textarea'],
        'OG Desc'    => ['type' => 'textarea'],
        'Reservation'    => ['type' => 'select', 'options' => ['Yes', 'No']],
        'Take away'      => ['type' => 'select', 'options' => ['Yes', 'No']],
        'Marquee active' => ['type' => 'select', 'options' => ['Yes', 'No']],
        'loginscrn' => [
            'type' => 'select',
            'label' => 'Show Login Screen for Inventory',
            'options' => ['yes' => 'Yes — require login', 'no' => 'No — go straight to Diamond Search'],
            'hint' => 'If set to No, the "Inventory" link on the home page skips login entirely and goes straight into the user module (public browsing). Admin/Super Admin logins are unaffected — once this is No, the admin login page is no longer linked anywhere on the public site, so log in directly at yoursite.com/login.php.',
        ],
    ],
    'path' => [
        'id' => ['type' => 'readonly'],
    ],
    'timings' => [
        'id'      => ['type' => 'readonly'],
        'Day'     => ['type' => 'select', 'options' => [
            'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday',
        ]],
        'holiday' => ['type' => 'select', 'options' => ['Yes', 'No']],
    ],
    'font_and_color' => [
        'id' => ['type' => 'readonly'],
        'font type-1' => ['type' => 'font_select', 'options' => FONT_CHOICES],
        'font type-2' => ['type' => 'font_select', 'options' => FONT_CHOICES],
        'font type-3' => ['type' => 'font_select', 'options' => FONT_CHOICES],
        'font type-4' => ['type' => 'font_select', 'options' => FONT_CHOICES],
        'font type-5' => ['type' => 'font_select', 'options' => FONT_CHOICES],
        'font-size-1' => ['hint' => 'Include a unit, e.g. "16px" or "1.2rem" — a bare number like "16" is not valid CSS.'],
        'font-size-2' => ['hint' => 'Include a unit, e.g. "16px" or "1.2rem".'],
        'font-size-3' => ['hint' => 'Include a unit, e.g. "16px" or "1.2rem".'],
        'font-size-4' => ['hint' => 'Include a unit, e.g. "16px" or "1.2rem".'],
        'font-size-5' => ['hint' => 'Include a unit, e.g. "16px" or "1.2rem".'],
        'selected_fonttype'  => ['type' => 'select', 'label' => 'Active Font Type',
                                  'options' => ['font type-1', 'font type-2', 'font type-3', 'font type-4', 'font type-5'],
                                  'hint' => 'Pick which of the 5 font-type slots above is used on the public site.'],
        'selected_fontsize'  => ['type' => 'select', 'label' => 'Active Font Size',
                                  'options' => ['font-size-1', 'font-size-2', 'font-size-3', 'font-size-4', 'font-size-5'],
                                  'hint' => 'Pick which of the 5 font-size slots above is used on the public site.'],
        'selected_forecolor' => ['type' => 'select', 'label' => 'Active Text Color',
                                  'options' => ['forecolor-1', 'forecolor-2', 'forecolor-3', 'forecolor-4', 'forecolor-5'],
                                  'hint' => 'Pick which of the 5 text-color slots above is used on the public site.'],
        'selected_backcolor' => ['type' => 'select', 'label' => 'Active Background Color',
                                  'options' => ['backcolor-1', 'backcolor-2', 'backcolor-3', 'backcolor-4', 'backcolor-5'],
                                  'hint' => 'Pick which of the 5 background-color slots above is used on the public site.'],
    ],
    'upload' => [
        'id'              => ['type' => 'readonly'],
        'API'             => ['type' => 'select', 'options' => ['Yes', 'No']],
        'Excel'           => ['type' => 'select', 'options' => ['Yes', 'No']],
        'CSV'             => ['type' => 'select', 'options' => ['Yes', 'No']],
        'API key'         => ['type' => 'secret', 'label' => 'API Key'],
        'API secret key'  => ['type' => 'secret', 'label' => 'API Secret Key'],
    ],
    'maindata' => [
        // `id` is intentionally left without an override: it is NOT
        // auto-increment (ids come from your data source), so it must
        // stay an editable required field on both add and edit.
    ],
    'diamond_search' => [
        'id'     => ['type' => 'readonly'],
        'active' => ['type' => 'select', 'label' => 'Active', 'options' => ['yes', 'no']],
        'orderid' => ['label' => 'Order Id', 'hint' => 'Controls display order — lower numbers appear first.'],
    ],
    'results' => [
        'id'     => ['type' => 'readonly'],
        'active' => ['type' => 'select', 'label' => 'Active', 'options' => ['yes', 'no']],
        'orderid' => ['label' => 'Order Id', 'hint' => 'Controls display order — lower numbers appear first.'],
    ],
    'diamond_details' => [
        'id'     => ['type' => 'readonly'],
        'active' => ['type' => 'select', 'label' => 'Active', 'options' => ['yes', 'no']],
        'orderid' => ['label' => 'Order Id', 'hint' => 'Controls display order — lower numbers appear first.'],
        'data_type' => ['label' => 'Data Type', 'hint' => 'e.g. text, integer, numeric — matches the source field\'s data type.'],
    ],
    'adv_filter' => [
        'id'     => ['type' => 'readonly'],
        'active' => ['type' => 'select', 'label' => 'Active', 'options' => ['yes', 'no']],
        'orderid' => ['label' => 'Order Id', 'hint' => 'Controls display order — lower numbers appear first.'],
    ],
    'customer' => [
        'custid' => ['type' => 'readonly'],
    ],
    'rsetup' => [
        'id'         => ['type' => 'readonly'],
        'fontype'    => ['type' => 'font_select', 'label' => 'Font Type', 'options' => FONT_CHOICES],
        'fontsize'   => ['label' => 'Font Size'],
        'sortfld1'   => ['type' => 'maindata_column_select', 'label' => 'Sort Field 1'],
        'sortorder1' => ['type' => 'select', 'label' => 'Sort Order 1', 'options' => ['A' => 'Ascending', 'D' => 'Descending']],
        'sortfld2'   => ['type' => 'maindata_column_select', 'label' => 'Sort Field 2'],
        'sortorder2' => ['type' => 'select', 'label' => 'Sort Order 2', 'options' => ['A' => 'Ascending', 'D' => 'Descending']],
        'sortfld3'   => ['type' => 'maindata_column_select', 'label' => 'Sort Field 3'],
        'sortorder3' => ['type' => 'select', 'label' => 'Sort Order 3', 'options' => ['A' => 'Ascending', 'D' => 'Descending']],
        'sortfld4'   => ['type' => 'maindata_column_select', 'label' => 'Sort Field 4'],
        'sortorder4' => ['type' => 'select', 'label' => 'Sort Order 4', 'options' => ['A' => 'Ascending', 'D' => 'Descending']],
        'sortfld5'   => ['type' => 'maindata_column_select', 'label' => 'Sort Field 5'],
        'sortorder5' => ['type' => 'select', 'label' => 'Sort Order 5', 'options' => ['A' => 'Ascending', 'D' => 'Descending']],
        'sortfld6'   => ['type' => 'maindata_column_select', 'label' => 'Sort Field 6'],
        'sortorder6' => ['type' => 'select', 'label' => 'Sort Order 6', 'options' => ['A' => 'Ascending', 'D' => 'Descending']],
    ],
<<<<<<< HEAD
    'uploadref' => [
        'id'        => ['type' => 'readonly'],
        'colname'   => ['type' => 'maindata_column_select', 'label' => 'Maindata Column'],
        'excolname' => ['label' => 'CSV Header Name', 'hint' => 'The exact column header your supplier\'s CSV file uses for this field.'],
        'active'    => ['type' => 'select', 'label' => 'Active', 'options' => ['yes' => 'Yes', 'no' => 'No']],
    ],
=======
>>>>>>> 6c80fa6d4f8fbd6bed0b28df715056898608f570
    'memo' => [
        'id' => ['type' => 'readonly'],
        'company' => ['label' => 'Company (masthead + "Firm" name)'],
        'address' => ['label' => 'Address (masthead line 1)'],
        'telno' => ['label' => 'Telephone (masthead line 2)'],
        'fax' => ['label' => 'Fax (masthead line 2)'],
        'gsm' => ['label' => 'GSM / Mobile (masthead line 2)'],
        'email' => ['label' => 'Email (masthead line 3)'],
        'web' => ['label' => 'Website (masthead line 3)'],
        'field1' => ['label' => 'Received-by label'],
        'field2' => ['label' => 'Company line (right)'],
        'field3' => ['label' => 'Signature label'],
        'field4' => ['label' => 'Extra line (right)'],
        'field5' => ['label' => 'Extra line (left)'],
        'field6' => ['type' => 'textarea', 'label' => 'Terms & conditions text'],
        'dated' => ['label' => 'Dated (unix timestamp)'],
    ],
    'dmemo' => [
        'id' => ['type' => 'readonly'],
        'company' => ['label' => 'Company (masthead + "Firm" name)'],
        'address' => ['label' => 'Address (masthead line 1)'],
        'telno' => ['label' => 'Telephone (masthead line 2)'],
        'fax' => ['label' => 'Fax (masthead line 2)'],
        'gsm' => ['label' => 'GSM / Mobile (masthead line 2)'],
        'email' => ['label' => 'Email (masthead line 3)'],
        'web' => ['label' => 'Website (masthead line 3)'],
        'field1' => ['label' => 'Received-by label'],
        'field2' => ['label' => 'Company line (right)'],
        'field3' => ['label' => 'Signature label'],
        'field4' => ['label' => 'Extra line (right)'],
        'field5' => ['label' => 'Extra line (left)'],
        'field6' => ['type' => 'textarea', 'label' => 'Terms & conditions text'],
        'dated' => ['label' => 'Dated (unix timestamp)'],
    ],
    'cut' => [
        'id'     => ['type' => 'readonly'],
        'active' => ['type' => 'select', 'options' => ['yes', 'no']],
    ],
    'fluorescence' => [
        'id'     => ['type' => 'readonly'],
        'active' => ['type' => 'select', 'options' => ['yes', 'no']],
    ],
    'polish' => [
        'id'     => ['type' => 'readonly'],
        'active' => ['type' => 'select', 'options' => ['yes', 'no']],
    ],
    'symmetry' => [
        'id'     => ['type' => 'readonly'],
        'active' => ['type' => 'select', 'options' => ['yes', 'no']],
    ],
    'shape' => [
        'id'     => ['type' => 'readonly'],
        'active' => ['type' => 'select', 'options' => ['yes', 'no']],
        'Display _nm' => ['label' => 'Display Name'],
    ],
    'location' => [
        'id'     => ['type' => 'readonly'],
        'active' => ['type' => 'select', 'options' => ['yes', 'no']],
    ],
    'availability' => [
        'id'      => ['type' => 'readonly'],
        'shortnm' => ['label' => 'Short Name', 'hint' => 'Matched against maindata\'s avail value to look up this row\'s color for the Stock No background on Results/View Cart.'],
        'color'   => ['type' => 'color', 'label' => 'Badge Color'],
        'active'  => ['type' => 'select', 'options' => ['yes', 'no']],
    ],
    'size' => [
        // `id` is intentionally left without an override: it is NOT
        // auto-increment (ids come from your data source), so it must
        // stay an editable required field on both add and edit.
    ],
    'lab' => [
        'id'     => ['type' => 'readonly'],
        'active' => ['type' => 'select', 'options' => ['yes', 'no']],
    ],
    'clarity' => [
        'id'     => ['type' => 'readonly'],
        'active' => ['type' => 'select', 'options' => ['yes', 'no']],
    ],
    'color' => [
        'id'     => ['type' => 'readonly'],
        'active' => ['type' => 'select', 'options' => ['yes', 'no']],
    ],
];

/** Columns of type 'forecolor-N' / 'backcolor-N' render as color pickers. */
function crud_is_color_column(string $column): bool
{
    return (bool)preg_match('/^(forecolor|backcolor)-\d+$/', $column);
}

/**
 * Explicit column choice + order for the list view, per table.
 * Tables not listed here fall back to "first N visible columns".
 */
const CRUD_LIST_COLUMNS = [
    'user'           => ['id', 'username', 'emailid', 'company', 'usertype', 'approval', 'last_login'],
    'user_types'     => ['id', 'usertype', 'level'],
    'setup'          => ['id', 'company', 'Page title', 'emailid1', 'telno-1'],
    'path'           => ['id', 'description', 'path'],
<<<<<<< HEAD
    'uploadref'      => ['id', 'colname', 'excolname', 'active'],
=======
>>>>>>> 6c80fa6d4f8fbd6bed0b28df715056898608f570
    'timings'        => ['id', 'Day', 'start time1', 'end time1', 'holiday'],
    'font_and_color' => ['id', 'font type-1', 'forecolor-1', 'backcolor-1'],
    'upload'         => ['id', 'API', 'API link', 'Excel', 'CSV'],
    'maindata'       => ['id', 'StockNo', 'Shape', 'Weight', 'Color', 'Clarity', 'CutGrade', 'Price', 'avail'],
    'diamond_search' => ['id', 'colname', 'fldname', 'active', 'orderid'],
    'results'        => ['id', 'colname', 'fldname', 'active', 'orderid'],
    'diamond_details' => ['id', 'colname', 'fldname', 'data_type', 'active', 'orderid'],
    'adv_filter'      => ['id', 'colname', 'fldname', 'active', 'orderid'],
    'customer'        => ['custid', 'custnm', 'shortnm', 'email', 'address'],
    'rsetup'          => ['id', 'fontype', 'fontsize', 'sortfld1', 'sortorder1'],
    'memo'            => ['id', 'company', 'address', 'telno', 'email'],
    'dmemo'           => ['id', 'company', 'address', 'telno', 'email'],
    'cut'            => ['id', 'cut_id', 'cut', 'order', 'active'],
    'fluorescence'   => ['id', 'flu_id', 'flu', 'order', 'active'],
    'polish'         => ['id', 'pol_id', 'pol', 'order', 'active'],
    'symmetry'       => ['id', 'sym_id', 'sym', 'order', 'active'],
    'shape'          => ['id', 'shape_id', 'shape', 'order', 'Display _nm', 'imgpath', 'active'],
    'location'       => ['id', 'location', 'loc_id', 'shortnm', 'active', 'order'],
    'size'           => ['id', 'sizedesc', 'sizefr', 'sizeto'],
    'lab'            => ['id', 'lab', 'active'],
    'clarity'        => ['id', 'clarity', 'active'],
    'color'          => ['id', 'color', 'active'],
    'availability'   => ['id', 'avail', 'shortnm', 'color', 'active', 'order'],
];

