-- ============================================================
-- Migration: add `size` and `lab` tables (from size.sql / lab.sql).
--
-- `size` — id is NOT auto-increment (manually assigned in the
-- source dump), matching how `maindata` was handled: ids come from
-- your own data, not generated by the app.
-- `lab`  — id IS auto-increment, with a unique constraint on `lab`
-- (e.g. can't have two rows both named "GIA").
--
-- Charset changed from the source dump's latin1 to utf8mb4 to match
-- the rest of this app's schema — safe here since all the data is
-- plain ASCII.
--
-- Safe to run once in phpMyAdmin's SQL tab against your existing
-- database.
-- ============================================================

CREATE TABLE IF NOT EXISTS `size` (
    `id`       INT NOT NULL,
    `sizedesc` VARCHAR(50) NOT NULL,
    `sizefr`   DECIMAL(10,2) NOT NULL,
    `sizeto`   DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `size` (`id`, `sizedesc`, `sizefr`, `sizeto`) VALUES
(2, '0.01-0.99', 0.01, 0.99),
(3, '0.90-0.99', 0.90, 0.99),
(4, '1.00-1.49', 1.00, 1.49),
(5, '1.50-1.99', 1.50, 1.99),
(6, '2.00-2.99', 2.00, 2.99),
(7, '3.00-3.99', 3.00, 3.99),
(8, '4.00-4.99', 4.00, 4.99),
(9, '5.00-5.99', 5.00, 5.99),
(10, '6.00-6.99', 6.00, 6.99),
(11, '7.00-7.99', 7.00, 7.99),
(12, '8.00-8.99', 8.00, 8.99),
(13, '9.00-9.99', 9.00, 9.99),
(14, '10 UP', 10.00, 99999.99);

CREATE TABLE IF NOT EXISTS `lab` (
    `id`  INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `lab` VARCHAR(10) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `lab` (`lab`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 AUTO_INCREMENT=6;

INSERT INTO `lab` (`id`, `lab`) VALUES
(5, 'AGS'),
(1, 'ALL'),
(4, 'GIA'),
(2, 'HRD'),
(3, 'IGI');
