-- ============================================================
-- Migration: add the `maindata` and `diamond_search` tables.
--
-- `maindata` holds diamond inventory records, one column per field
-- from the supplied field-definition spreadsheet (93 fields), with
-- `id` as the primary key. It is NOT auto-increment — ids are
-- expected to come from your data source (e.g. an import file),
-- so always supply an id when adding a new record.
--
-- `diamond_search` is a small metadata table listing every column
-- in `maindata` (colname/fldname), whether it's active, and its
-- display order — seeded below from maindata's own field list.
--
-- Safe to run once in phpMyAdmin's SQL tab against your existing
-- database.
-- ============================================================

CREATE TABLE IF NOT EXISTS maindata (
    `altprice`                   DECIMAL(14,2) NULL,
    `avail`                      VARCHAR(255) NULL,
    `bgm`                        VARCHAR(255) NULL,
    `black_incl`                 VARCHAR(255) NULL,
    `brand`                      VARCHAR(255) NULL,
    `Cash discount`              DECIMAL(14,2) NULL,
    `Cash price`                 DECIMAL(14,2) NULL,
    `cert_comment`               TEXT NULL,
    `CertificateImage`           TEXT NULL,
    `CertificateNo`              VARCHAR(255) NULL,
    `CityStateCountry`           VARCHAR(255) NULL,
    `Clarity`                    VARCHAR(255) NULL,
    `clremark`                   VARCHAR(255) NULL,
    `Color`                      VARCHAR(255) NULL,
    `CrownAngle`                 VARCHAR(255) NULL,
    `CrownHeight`                VARCHAR(255) NULL,
    `CuletCondition`             VARCHAR(255) NULL,
    `CuletSize`                  VARCHAR(255) NULL,
    `CutGrade`                   VARCHAR(255) NULL,
    `Depthpct`                   DECIMAL(14,2) NULL,
    `eyeclean`                   VARCHAR(255) NULL,
    `Fancycolor`                 VARCHAR(255) NULL,
    `FluorescenceColor`          VARCHAR(255) NULL,
    `FluorescenceIntensity`      VARCHAR(255) NULL,
    `fluoroth`                   VARCHAR(255) NULL,
    `Girdlecond`                 VARCHAR(255) NULL,
    `Girdlepct`                  DECIMAL(14,2) NULL,
    `GirdleThinorGirdleThick`    VARCHAR(255) NULL,
    `height`                     DECIMAL(14,2) NULL,
    `hold`                       VARCHAR(255) NULL,
    `id`                         INT NOT NULL,
    `imglink`                    TEXT NULL,
    `keytosym`                   VARCHAR(255) NULL,
    `Lab`                        VARCHAR(255) NULL,
    `LaserInscription`           VARCHAR(255) NULL,
    `length`                     DECIMAL(14,2) NULL,
    `list`                       VARCHAR(255) NULL,
    `location`                   VARCHAR(255) NULL,
    `lotno`                      VARCHAR(255) NULL,
    `Measurements`               TEXT NULL,
    `Member_Comment`             TEXT NULL,
    `milkyid`                    INT NULL,
    `mkamt`                      DECIMAL(14,2) NULL,
    `mkdis`                      DECIMAL(14,2) NULL,
    `mkprice`                    DECIMAL(14,2) NULL,
    `NatFancyColor`              VARCHAR(255) NULL,
    `NatFancyColorIntensity`     VARCHAR(255) NULL,
    `NatFancyColorOvertone`      VARCHAR(255) NULL,
    `notforweb`                  VARCHAR(255) NULL,
    `open inclusion`             VARCHAR(255) NULL,
    `orapprice`                  DECIMAL(14,2) NULL,
    `origin`                     VARCHAR(255) NULL,
    `Pair`                       VARCHAR(255) NULL,
    `pairnm`                     VARCHAR(255) NULL,
    `PairSeparable`              VARCHAR(255) NULL,
    `parcel`                     VARCHAR(255) NULL,
    `ParcelStoneCount`           INT NULL,
    `PavilionAngle`              DECIMAL(14,2) NULL,
    `PavilionDepth`              DECIMAL(14,2) NULL,
    `pcs`                        INT NULL,
    `pdflink`                    TEXT NULL,
    `Polish`                     VARCHAR(255) NULL,
    `Price`                      DECIMAL(14,2) NULL,
    `Rap`                        DECIMAL(14,2) NULL,
    `RapOff`                     DECIMAL(14,2) NULL,
    `shadeid`                    INT NULL,
    `Shape`                      VARCHAR(255) NULL,
    `shapeoth`                   VARCHAR(255) NULL,
    `sizedesc`                   VARCHAR(255) NULL,
    `srtcla`                     INT NULL,
    `srtcol`                     INT NULL,
    `srtcts`                     INT NULL,
    `srtcut`                     INT NULL,
    `srtflu`                     INT NULL,
    `srtloc`                     INT NULL,
    `srtpol`                     INT NULL,
    `srtshp`                     INT NULL,
    `srtsiz`                     INT NULL,
    `srtsym`                     INT NULL,
    `starlength`                 VARCHAR(255) NULL,
    `statusid`                   INT NULL,
    `StockNo`                    VARCHAR(255) NULL,
    `Symmetry`                   VARCHAR(255) NULL,
    `table_incl`                 VARCHAR(255) NULL,
    `Tablepct`                   DECIMAL(14,2) NULL,
    `totamt`                     DECIMAL(14,2) NULL,
    `TradeShow`                  VARCHAR(255) NULL,
    `TreatmentLD`                VARCHAR(255) NULL,
    `vidlink`                    TEXT NULL,
    `viewyn`                     VARCHAR(255) NULL,
    `Weight`                     DECIMAL(14,2) NULL,
    `white inclusion`            VARCHAR(255) NULL,
    `width`                      DECIMAL(14,2) NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS diamond_search (
    id       INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    colname  VARCHAR(255) NOT NULL,
    fldname  VARCHAR(255) NOT NULL,
    active   VARCHAR(10) NOT NULL DEFAULT 'yes',
    orderid  INT NOT NULL
) ENGINE=InnoDB;

-- Seed diamond_search from maindata's field list. colname/fldname
-- start identical, and id/orderid start identical, per spec.
INSERT INTO diamond_search (id, colname, fldname, active, orderid) VALUES
(1, 'altprice', 'altprice', 'yes', 1),
(2, 'avail', 'avail', 'yes', 2),
(3, 'bgm', 'bgm', 'yes', 3),
(4, 'black_incl', 'black_incl', 'yes', 4),
(5, 'brand', 'brand', 'yes', 5),
(6, 'Cash discount', 'Cash discount', 'yes', 6),
(7, 'Cash price', 'Cash price', 'yes', 7),
(8, 'cert_comment', 'cert_comment', 'yes', 8),
(9, 'CertificateImage', 'CertificateImage', 'yes', 9),
(10, 'CertificateNo', 'CertificateNo', 'yes', 10),
(11, 'CityStateCountry', 'CityStateCountry', 'yes', 11),
(12, 'Clarity', 'Clarity', 'yes', 12),
(13, 'clremark', 'clremark', 'yes', 13),
(14, 'Color', 'Color', 'yes', 14),
(15, 'CrownAngle', 'CrownAngle', 'yes', 15),
(16, 'CrownHeight', 'CrownHeight', 'yes', 16),
(17, 'CuletCondition', 'CuletCondition', 'yes', 17),
(18, 'CuletSize', 'CuletSize', 'yes', 18),
(19, 'CutGrade', 'CutGrade', 'yes', 19),
(20, 'Depthpct', 'Depthpct', 'yes', 20),
(21, 'eyeclean', 'eyeclean', 'yes', 21),
(22, 'Fancycolor', 'Fancycolor', 'yes', 22),
(23, 'FluorescenceColor', 'FluorescenceColor', 'yes', 23),
(24, 'FluorescenceIntensity', 'FluorescenceIntensity', 'yes', 24),
(25, 'fluoroth', 'fluoroth', 'yes', 25),
(26, 'Girdlecond', 'Girdlecond', 'yes', 26),
(27, 'Girdlepct', 'Girdlepct', 'yes', 27),
(28, 'GirdleThinorGirdleThick', 'GirdleThinorGirdleThick', 'yes', 28),
(29, 'height', 'height', 'yes', 29),
(30, 'hold', 'hold', 'yes', 30),
(31, 'id', 'id', 'yes', 31),
(32, 'imglink', 'imglink', 'yes', 32),
(33, 'keytosym', 'keytosym', 'yes', 33),
(34, 'Lab', 'Lab', 'yes', 34),
(35, 'LaserInscription', 'LaserInscription', 'yes', 35),
(36, 'length', 'length', 'yes', 36),
(37, 'list', 'list', 'yes', 37),
(38, 'location', 'location', 'yes', 38),
(39, 'lotno', 'lotno', 'yes', 39),
(40, 'Measurements', 'Measurements', 'yes', 40),
(41, 'Member_Comment', 'Member_Comment', 'yes', 41),
(42, 'milkyid', 'milkyid', 'yes', 42),
(43, 'mkamt', 'mkamt', 'yes', 43),
(44, 'mkdis', 'mkdis', 'yes', 44),
(45, 'mkprice', 'mkprice', 'yes', 45),
(46, 'NatFancyColor', 'NatFancyColor', 'yes', 46),
(47, 'NatFancyColorIntensity', 'NatFancyColorIntensity', 'yes', 47),
(48, 'NatFancyColorOvertone', 'NatFancyColorOvertone', 'yes', 48),
(49, 'notforweb', 'notforweb', 'yes', 49),
(50, 'open inclusion', 'open inclusion', 'yes', 50),
(51, 'orapprice', 'orapprice', 'yes', 51),
(52, 'origin', 'origin', 'yes', 52),
(53, 'Pair', 'Pair', 'yes', 53),
(54, 'pairnm', 'pairnm', 'yes', 54),
(55, 'PairSeparable', 'PairSeparable', 'yes', 55),
(56, 'parcel', 'parcel', 'yes', 56),
(57, 'ParcelStoneCount', 'ParcelStoneCount', 'yes', 57),
(58, 'PavilionAngle', 'PavilionAngle', 'yes', 58),
(59, 'PavilionDepth', 'PavilionDepth', 'yes', 59),
(60, 'pcs', 'pcs', 'yes', 60),
(61, 'pdflink', 'pdflink', 'yes', 61),
(62, 'Polish', 'Polish', 'yes', 62),
(63, 'Price', 'Price', 'yes', 63),
(64, 'Rap', 'Rap', 'yes', 64),
(65, 'RapOff', 'RapOff', 'yes', 65),
(66, 'shadeid', 'shadeid', 'yes', 66),
(67, 'Shape', 'Shape', 'yes', 67),
(68, 'shapeoth', 'shapeoth', 'yes', 68),
(69, 'sizedesc', 'sizedesc', 'yes', 69),
(70, 'srtcla', 'srtcla', 'yes', 70),
(71, 'srtcol', 'srtcol', 'yes', 71),
(72, 'srtcts', 'srtcts', 'yes', 72),
(73, 'srtcut', 'srtcut', 'yes', 73),
(74, 'srtflu', 'srtflu', 'yes', 74),
(75, 'srtloc', 'srtloc', 'yes', 75),
(76, 'srtpol', 'srtpol', 'yes', 76),
(77, 'srtshp', 'srtshp', 'yes', 77),
(78, 'srtsiz', 'srtsiz', 'yes', 78),
(79, 'srtsym', 'srtsym', 'yes', 79),
(80, 'starlength', 'starlength', 'yes', 80),
(81, 'statusid', 'statusid', 'yes', 81),
(82, 'StockNo', 'StockNo', 'yes', 82),
(83, 'Symmetry', 'Symmetry', 'yes', 83),
(84, 'table_incl', 'table_incl', 'yes', 84),
(85, 'Tablepct', 'Tablepct', 'yes', 85),
(86, 'totamt', 'totamt', 'yes', 86),
(87, 'TradeShow', 'TradeShow', 'yes', 87),
(88, 'TreatmentLD', 'TreatmentLD', 'yes', 88),
(89, 'vidlink', 'vidlink', 'yes', 89),
(90, 'viewyn', 'viewyn', 'yes', 90),
(91, 'Weight', 'Weight', 'yes', 91),
(92, 'white inclusion', 'white inclusion', 'yes', 92),
(93, 'width', 'width', 'yes', 93);
